<?php

$sql =<<<EOF
DROP TABLE IF EXISTS `ims_tiny_wmall_account`;
DROP TABLE IF EXISTS `ims_tiny_wmall_activity_coupon`;
DROP TABLE IF EXISTS `ims_tiny_wmall_activity_coupon_grant_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_activity_coupon_record`;
DROP TABLE IF EXISTS `ims_tiny_wmall_address`;
DROP TABLE IF EXISTS `ims_tiny_wmall_article`;
DROP TABLE IF EXISTS `ims_tiny_wmall_article_category`;
DROP TABLE IF EXISTS `ims_tiny_wmall_assign_board`;
DROP TABLE IF EXISTS `ims_tiny_wmall_assign_queue`;
DROP TABLE IF EXISTS `ims_tiny_wmall_black`;
DROP TABLE IF EXISTS `ims_tiny_wmall_clerk`;
DROP TABLE IF EXISTS `ims_tiny_wmall_config`;
DROP TABLE IF EXISTS `ims_tiny_wmall_delivery_cards`;
DROP TABLE IF EXISTS `ims_tiny_wmall_delivery_cards_order`;
DROP TABLE IF EXISTS `ims_tiny_wmall_delivery_config`;
DROP TABLE IF EXISTS `ims_tiny_wmall_deliveryer`;
DROP TABLE IF EXISTS `ims_tiny_wmall_deliveryer_current_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_deliveryer_getcash_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_fans`;
DROP TABLE IF EXISTS `ims_tiny_wmall_goods`;
DROP TABLE IF EXISTS `ims_tiny_wmall_goods_category`;
DROP TABLE IF EXISTS `ims_tiny_wmall_goods_options`;
DROP TABLE IF EXISTS `ims_tiny_wmall_members`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order_cart`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order_comment`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order_current_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order_discount`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order_print_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order_refund_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order_stat`;
DROP TABLE IF EXISTS `ims_tiny_wmall_order_status_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_paylog`;
DROP TABLE IF EXISTS `ims_tiny_wmall_printer`;
DROP TABLE IF EXISTS `ims_tiny_wmall_reply`;
DROP TABLE IF EXISTS `ims_tiny_wmall_report`;
DROP TABLE IF EXISTS `ims_tiny_wmall_reserve`;
DROP TABLE IF EXISTS `ims_tiny_wmall_slide`;
DROP TABLE IF EXISTS `ims_tiny_wmall_sms_send_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_account`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_activity`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_category`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_current_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_delivery_times`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_deliveryer`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_favorite`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_getcash_log`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_members`;
DROP TABLE IF EXISTS `ims_tiny_wmall_store_settle_config`;
DROP TABLE IF EXISTS `ims_tiny_wmall_tables`;
DROP TABLE IF EXISTS `ims_tiny_wmall_tables_category`;
DROP TABLE IF EXISTS `ims_tiny_wmall_tables_scan`;

EOF;
pdo_run($sql);